### ISSUE TITLE
404 handling broken

### ISSUE THREAD

**Issue by misterboe** [b13/uniquealiasmapper#8]
typo3/cms-core: ^10
b13/uniquealiasmapper: ^1.1

I use uniquealiasmapper to show detail pages of products. As soon as i add the Code to the config.yaml the urls look nice, but the 404 handling is not working anymore. None URL's like 'https://tdl.de/xyz' show rootpage of the web instead of the 404 page which is configured in the siteconfig. Status is 200.  

```
  ProductExample:
    type: Simple
    routePath: '/{product}'
    _arguments:
      product: product
    aspects:
      product:
        type: UniqueAlias
        tableName: 'tx_product'
        aliasField: 'header'
        expires: '15d'
        uniqueConfiguration:
          fallbackCharacter: '-'
```
